name: Generate Cargo.lock

on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sfgame_reader

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Upload Cargo.lock
        uses: actions/upload-artifact@v4
        with:
          name: cargo-lock
          path: sfgame_reader/Cargo.lock
